---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dongzhi.
--- DateTime: 2024/2/4 11:48
---
---

local hello = function ()
    ngx.say("host111:"..ngx.var.host)
    ngx.say("Hello world,Luaqqssss!")
    ngx.log(ngx.NOTICE, "i am debugdd !")
    require("debug.test")

end

hello()
